PS1='%(?..(%?%))%# '
setopt EXTENDED_GLOB EXTENDED_HISTORY INC_APPEND_HISTORY APPEND_HISTORY HIST_IGNORE_SPACE HIST_NO_STORE
setopt NO_NOMATCH
[[ -v INSIDE_EMACS ]] && setopt NO_ZLE

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.history

alias odz='od -tx1z'
bindkey -e
